services:
  db:
    image: postgres:17-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: medicines_db
      TZ: Europe/Moscow
      POSTGRES_INITDB_ARGS: "--locale=ru_RU.UTF-8 --lc-collate=C --encoding=UTF-8"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d medicines_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: rabbitmq_medicines
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS}
      RABBITMQ_VM_MEMORY_HIGH_WATERMARK: "0.4"
      TZ: Europe/Moscow
    mem_limit: 512m
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app_network
    restart: unless-stopped

  backend:
    build:
      context: ./spring-medicines
      dockerfile: Dockerfile
    container_name: app_back_medicine
    environment:
      BASE_URL: ${BASE_URL}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_SET_FROM: ${MAIL_SET_FROM}
      MAIL_TO: ${MAIL_TO}

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
      YANDEX_CLIENT_ID: ${YANDEX_CLIENT_ID}
      YANDEX_CLIENT_SECRET: ${YANDEX_CLIENT_SECRET}
      YANDEX_REDIRECT_URI: ${YANDEX_REDIRECT_URI}
      SUCCESS_REDIRECT: ${SUCCESS_REDIRECT}
      FAILURE_REDIRECT: ${FAILURE_REDIRECT}
      TZ: Europe/Moscow
    ports:
      - "8080:8080"
    networks:
      - app_network
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 5s

  frontend:
    build:
      context: ./spring-frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_YANDEX_AUTH: ${VITE_YANDEX_AUTH}
    container_name: app_front_medicine
    ports:
      - "8081:80"
    depends_on:
      - backend
    environment:
      TZ: Europe/Moscow
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  pg_data: {}
